In [1]:
import pandas as pd
import pandas_ta as ta
import numpy as np
import yfinance as yf
import vectorbt as vbt
from datetime import datetime

In [8]:
data = pd.DataFrame()
data = data.ta.ticker('EURUSD=x',period='5y')

In [9]:
df = data.copy()

In [10]:
df.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2017-03-06,1.061875,1.063807,1.057820,1.062045,0,0,0
2017-03-07,1.058123,1.060400,1.056078,1.057921,0,0,0
2017-03-08,1.056893,1.057530,1.053730,1.057015,0,0,0
2017-03-09,1.054407,1.061402,1.052565,1.054741,0,0,0
2017-03-10,1.058134,1.066906,1.058134,1.057843,0,0,0

In [11]:
df = data.copy()
df.ta.macd(12, 21, append=True)
df.columns

Index(['Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits',
       'MACD_12_21_9', 'MACDh_12_21_9', 'MACDs_12_21_9'],
      dtype='object')

In [16]:
df['signal'] = df.iloc[:,-3] > df.iloc[:,-1]
signal_vectorbt = df.ta.tsignals(df.signal, asbool=True, append=True)
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,MACD_12_21_9,MACDh_12_21_9,MACDs_12_21_9,signal,TS_Trends,TS_Trades,TS_Entries,TS_Exits
Date,,,,,,,,,,,,,,,
2017-03-06,1.061875,1.063807,1.057820,1.062045,0,0,0,NaN,NaN,NaN,False,False,0,False,False
2017-03-07,1.058123,1.060400,1.056078,1.057921,0,0,0,NaN,NaN,NaN,False,False,0,False,False
2017-03-08,1.056893,1.057530,1.053730,1.057015,0,0,0,NaN,NaN,NaN,False,False,0,False,False
2017-03-09,1.054407,1.061402,1.052565,1.054741,0,0,0,NaN,NaN,NaN,False,False,0,False,False
2017-03-10,1.058134,1.066906,1.058134,1.057843,0,0,0,NaN,NaN,NaN,False,False,0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-02-28,1.118105,1.124455,1.114318,1.118105,0,0,0,-0.001877,-0.001588,-0.000288,False,False,0,False,False
2022-03-01,1.121466,1.123217,1.110211,1.121592,0,0,0,-0.002210,-0.001537,-0.000673,False,False,0,False,False
2022-03-02,1.113102,1.114194,1.105852,1.113276,0,0,0,-0.002959,-0.001829,-0.001130,False,False,0,False,False
2022-03-03,1.111358,1.111605,1.103984,1.111235,0,0,0,-0.003622,-0.001994,-0.001629,False,False,0,False,False
2022-03-04,1.107420,1.107542,1.089443,1.092299,0,0,0,-0.005274,-0.002916,-0.002358,False,False,0,False,False

In [17]:
df['action_price'] = df['Open'].shift(-1)
df.tail()

,Open,High,Low,Close,Volume,Dividends,Stock Splits,MACD_12_21_9,MACDh_12_21_9,MACDs_12_21_9,signal,TS_Trends,TS_Trades,TS_Entries,TS_Exits,action_price
Date,,,,,,,,,,,,,,,,
2022-02-28,1.118105,1.124455,1.114318,1.118105,0,0,0,-0.001877,-0.001588,-0.000288,False,False,0,False,False,1.121466
2022-03-01,1.121466,1.123217,1.110211,1.121592,0,0,0,-0.002210,-0.001537,-0.000673,False,False,0,False,False,1.113102
2022-03-02,1.113102,1.114194,1.105852,1.113276,0,0,0,-0.002959,-0.001829,-0.001130,False,False,0,False,False,1.111358
2022-03-03,1.111358,1.111605,1.103984,1.111235,0,0,0,-0.003622,-0.001994,-0.001629,False,False,0,False,False,1.107420
2022-03-04,1.107420,1.107542,1.089443,1.092299,0,0,0,-0.005274,-0.002916,-0.002358,False,False,0,False,False,NaN

In [70]:
d1 = df.iloc[:,-5:]
d2 = df.iloc[:,-1]
print(d1.head())
print(d2.head())

            TS_Trends  TS_Trades  TS_Entries  TS_Exits  action_price
Date
2017-03-06      False          0       False     False      1.058123
2017-03-07      False          0       False     False      1.056893
2017-03-08      False          0       False     False      1.054407
2017-03-09      False          0       False     False      1.058134
2017-03-10      False          0       False     False      1.068799
Date
2017-03-06    1.058123
2017-03-07    1.056893
2017-03-08    1.054407
2017-03-09    1.058134
2017-03-10    1.068799
Name: action_price, dtype: float64

In [71]:
trades_table = df.iloc[:,-5:][df.TS_Trades != 0]
trades_table

            TS_Trends  TS_Trades  TS_Entries  TS_Exits  action_price
Date
2017-04-20       True          1        True     False      1.071329
2017-05-11      False         -1       False      True      1.086602
2017-05-17       True          1        True     False      1.115424
2017-05-30      False         -1       False      True      1.117368
2017-06-28       True          1        True     False      1.137799
...               ...        ...         ...       ...           ...
2021-11-11      False         -1       False      True      1.144780
2021-12-01       True          1        True     False      1.131964
2022-01-21      False         -1       False      True      1.134095
2022-02-04       True          1        True     False      1.145462
2022-02-18      False         -1       False      True      1.131734

[118 rows x 5 columns]

In [20]:
trades_table['return'] = trades_table['action_price'].pct_change()
trades_table

            TS_Trends  TS_Trades  TS_Entries  TS_Exits  action_price    return
Date
2017-04-20       True          1        True     False      1.071329       NaN
2017-04-21      False         -1       False      True      1.087536  0.015128
2017-05-17       True          1        True     False      1.115424  0.025644
2017-05-18      False         -1       False      True      1.111086 -0.003889
2017-06-29       True          1        True     False      1.144047  0.029665
...               ...        ...         ...       ...           ...       ...
2021-11-10      False         -1       False      True      1.148567 -0.009315
2021-12-01       True          1        True     False      1.131964 -0.014455
2021-12-02      False         -1       False      True      1.130684 -0.001131
2022-02-04       True          1        True     False      1.145462  0.013070
2022-02-07      False         -1       False      True      1.144086 -0.001201

[112 rows x 6 columns]

In [22]:
#trades_summary = trades_table.reset_index().iloc[1::2]
trades_summary = trades_table.loc[trades_table.TS_Exits == True]
trades_summary

            TS_Trends  TS_Trades  TS_Entries  TS_Exits  action_price    return
Date
2017-04-21      False         -1       False      True      1.087536  0.015128
2017-05-18      False         -1       False      True      1.111086 -0.003889
2017-06-30      False         -1       False      True      1.142505 -0.001348
2017-08-30      False         -1       False      True      1.189004 -0.006706
2017-09-11      False         -1       False      True      1.195858 -0.004724
2017-10-13      False         -1       False      True      1.181502 -0.001382
2017-10-27      False         -1       False      True      1.160726 -0.002728
2017-11-14      False         -1       False      True      1.179176  0.010872
2017-12-22      False         -1       False      True      1.185677  0.000439
2018-01-16      False         -1       False      True      1.227144  0.000123
2018-03-09      False         -1       False      True      1.230860  0.000062
2018-03-15      False         -1       False      True      1.230769 -0.005465
2018-03-28      False         -1       False      True      1.231284 -0.007671
2018-04-12      False         -1       False      True      1.233350 -0.003453
2018-06-04      False         -1       False      True      1.170179  0.002727
2018-06-26      False         -1       False      True      1.164809 -0.004589
2018-08-01      False         -1       False      True      1.166385 -0.002204
2018-08-23      False         -1       False      True      1.154281 -0.003751
2018-09-14      False         -1       False      True      1.162358 -0.005719
2018-10-18      False         -1       False      True      1.145515 -0.003975
2018-11-07      False         -1       False      True      1.143328 -0.000674
2018-11-20      False         -1       False      True      1.137268 -0.007165
2019-01-09      False         -1       False      True      1.155522  0.008551
2019-02-01      False         -1       False      True      1.145725  0.000561
2019-02-25      False         -1       False      True      1.136622  0.002296
2019-03-18      False         -1       False      True      1.133556  0.001383
2019-04-11      False         -1       False      True      1.125936 -0.001486
2019-05-08      False         -1       False      True      1.119746  0.000705
2019-05-28      False         -1       False      True      1.117069 -0.002044
2019-06-05      False         -1       False      True      1.122725 -0.002470
2019-06-25      False         -1       False      True      1.136855 -0.002774
2019-08-07      False         -1       False      True      1.120486 -0.000090
2019-09-11      False         -1       False      True      1.101443 -0.003194
2019-10-08      False         -1       False      True      1.096022 -0.001140
2019-12-04      False         -1       False      True      1.108267  0.000078
2019-12-31      False         -1       False      True      1.122083  0.001459
2020-02-27      False         -1       False      True      1.099554  0.010094
2020-04-01      False         -1       False      True      1.095098 -0.006998
2020-04-14      False         -1       False      True      1.098237  0.005755
2020-05-01      False         -1       False      True      1.095746  0.001162
2020-05-14      False         -1       False      True      1.080625 -0.001448
2020-05-20      False         -1       False      True      1.097936  0.004502
2020-07-16      False         -1       False      True      1.138650 -0.002702
2020-10-07      False         -1       False      True      1.176554  0.002400
2020-10-21      False         -1       False      True      1.185129  0.001861
2020-11-09      False         -1       False      True      1.182327 -0.005876
2021-02-12      False         -1       False      True      1.212106 -0.000739
2021-04-07      False         -1       False      True      1.187197 -0.000297
2021-05-11      False         -1       False      True      1.214550  0.000279
2021-05-19      False         -1       False      True      1.217285 -0.004382
2021-07-13      False         -1       False      True      1.177440 -0.007630
2021-08-26      False         -1       False      True      1.175295 -0.001703
2021-10-18      False         -1       False      True      1.161454  0.001603
2021-11-10      False         -1       False      True      1.148567 -0.009315
2021-12-02      False         -1       False      True      1.130684 -0.001131
2022-02-07      False         -1       False      True      1.144086 -0.001201

In [72]:
compare = []
trade_log = []

for i in range(11, 15):
    for j in range(21, 25):
        #Reset dataframe
        df = data.copy()
        
        #Run MACD
        df.ta.macd(fast=i, slow=j, append=True)
        
        #Create signal
        df['signal'] = df.iloc[:,-3] > df.iloc[:,-1]
        
        #Create TS table
        signal_vectorbt = df.ta.tsignals(df.signal, asbool=True, append=True)
        
        #Action on the next open
        df['action_price'] = df['Open'].shift(-1)
        
        #Create trading logs
        trades_table = df.iloc[:,-5:][df.TS_Trades != 0]
        trades_table['return'] = trades_table['action_price'].pct_change()
        trades_summary = trades_table.loc[trades_table.TS_Exits == True]
        
        #Select data for comparing
        a = trades_summary['return']
        trade_log.append(a)
        b = [a.mean(), a.median(), a.min(), (i,j)]
        compare.append(b)

In [73]:
compare

[[-0.0015419911226947495,
  -0.003652222346180789,
  -0.0199412242042476,
  (11, 21)],
 [-0.0017648823001152796,
  -0.003842544764049549,
  -0.0199412242042476,
  (11, 22)],
 [-0.001804634745439257, -0.003974968756552788, -0.0199412242042476, (11, 23)],
 [-0.0016402031492183968,
  -0.0037101207715463103,
  -0.0199412242042476,
  (11, 24)],
 [-0.001780507822330716,
  -0.0045294580010991625,
  -0.0199412242042476,
  (12, 21)],
 [-0.0016411881236410273,
  -0.0037101207715463103,
  -0.0199412242042476,
  (12, 22)],
 [-0.0016512618816160193,
  -0.003652222346180789,
  -0.0199412242042476,
  (12, 23)],
 [-0.0016298885479897904,
  -0.0036811715588635496,
  -0.0199412242042476,
  (12, 24)],
 [-0.001696786364774039, -0.003652222346180789, -0.0199412242042476, (13, 21)],
 [-0.0016604807188849878,
  -0.003702090196795571,
  -0.0199412242042476,
  (13, 22)],
 [-0.0011600517414676727,
  -0.0037667804379762915,
  -0.0199412242042476,
  (13, 23)],
 [-0.0010606429095336145,
  -0.003751958047410353,
  -0.0199412242042476,
  (13, 24)],
 [-0.0013175974149464574,
  -0.0037667804379762915,
  -0.0199412242042476,
  (14, 21)],
 [-0.0010389774041260746,
  -0.003751958047410353,
  -0.015983293464378767,
  (14, 22)],
 [-0.0009349650669022612,
  -0.0027277089528812137,
  -0.015983293464378767,
  (14, 23)],
 [-0.0011453207688066672,
  -0.00378160282854223,
  -0.015787274142333718,
  (14, 24)]]

In [74]:
trade_log

[Date
 2017-05-11    0.014256
 2017-05-30    0.001743
 2017-08-09    0.033988
 2017-09-04   -0.006340
 2017-09-13   -0.010392
 2017-10-25   -0.000780
 2017-10-27   -0.002728
 2017-12-07    0.009384
 2018-01-10    0.008715
 2018-02-06    0.009088
 2018-03-12    0.002505
 2018-03-16   -0.007639
 2018-03-30   -0.007671
 2018-04-23   -0.013335
 2018-06-20   -0.007965
 2018-07-20    0.003417
 2018-07-30    0.000855
 2018-08-02   -0.008898
 2018-09-11    0.000835
 2018-09-28   -0.001602
 2018-10-18   -0.003975
 2018-11-13   -0.010920
 2019-01-04   -0.003652
 2019-01-16   -0.005084
 2019-02-07   -0.009684
 2019-03-07   -0.012188
 2019-03-27   -0.006053
 2019-04-24   -0.010566
 2019-05-21   -0.003079
 2019-05-30   -0.005687
 2019-06-18   -0.005117
 2019-07-03   -0.009843
 2019-08-19   -0.011005
 2019-09-26   -0.011458
 2019-11-06    0.008923
 2019-11-25   -0.001101
 2019-12-23    0.001009
 2020-01-09   -0.008499
 2020-03-18    0.005308
 2020-04-03   -0.019941
 2020-04-22   -0.010321
 2020-05-12   -0.008992
 2020-05-14   -0.001448
 2020-06-17    0.028463
 2020-08-11    0.028833
 2020-10-19    0.002612
 2020-10-30   -0.015787
 2020-12-23    0.025290
 2021-03-02   -0.003710
 2021-03-24   -0.002315
 2021-05-05    0.011253
 2021-05-13   -0.005098
 2021-05-28   -0.002974
 2021-08-10   -0.012235
 2021-09-15    0.003937
 2021-11-08   -0.000626
 2021-11-11   -0.012581
 2022-01-21    0.001883
 2022-02-18   -0.011985
 Name: return, dtype: float64,
 Date
 2017-05-11    0.014256
 2017-05-30    0.001743
 2017-08-09    0.028341
 2017-09-04   -0.006340
 2017-09-13   -0.010392
 2017-10-25   -0.000780
 2017-10-27   -0.002728
 2017-12-07    0.009384
 2018-01-10    0.008715
 2018-02-06    0.009088
 2018-03-12    0.002505
 2018-03-16   -0.007639
 2018-03-30   -0.007671
 2018-04-23   -0.013335
 2018-06-20   -0.007965
 2018-07-20    0.003417
 2018-07-30    0.000855
 2018-08-02   -0.008898
 2018-09-11    0.000835
 2018-10-01   -0.009656
 2018-10-18   -0.003975
 2018-11-13   -0.010920
 2019-01-04   -0.003652
 2019-01-16   -0.005084
 2019-02-07   -0.009684
 2019-03-07   -0.012188
 2019-03-27   -0.006053
 2019-04-24   -0.010566
 2019-05-21   -0.003079
 2019-05-30   -0.005687
 2019-06-18   -0.005117
 2019-07-03   -0.009843
 2019-08-19   -0.011005
 2019-09-26   -0.011458
 2019-11-06    0.008923
 2019-11-25   -0.001101
 2019-12-23    0.001009
 2020-01-09   -0.008499
 2020-03-18    0.005308
 2020-04-03   -0.019941
 2020-04-22   -0.010321
 2020-05-12   -0.008992
 2020-05-14   -0.001448
 2020-06-17    0.028463
 2020-08-11    0.028833
 2020-10-19    0.002612
 2020-10-30   -0.015787
 2020-12-23    0.025290
 2021-03-02   -0.003710
 2021-05-05    0.011253
 2021-05-13   -0.005098
 2021-05-28   -0.002974
 2021-08-10   -0.012235
 2021-09-15    0.003937
 2021-11-08   -0.000626
 2021-11-11   -0.012581
 2022-01-21    0.001883
 2022-02-18   -0.011985
 Name: return, dtype: float64,
 Date
 2017-05-11    0.014256
 2017-05-31    0.007530
 2017-08-09    0.028341
 2017-09-04   -0.006340
 2017-09-13   -0.010392
 2017-10-25   -0.000780
 2017-10-27   -0.002728
 2017-12-07    0.009384
 2018-01-10    0.008715
 2018-02-06    0.009088
 2018-03-12    0.002505
 2018-03-16   -0.007639
 2018-03-30   -0.007671
 2018-04-23   -0.013335
 2018-06-20   -0.007965
 2018-07-30    0.000585
 2018-08-02   -0.008898
 2018-09-11    0.000835
 2018-10-01   -0.009656
 2018-10-18   -0.003975
 2018-11-13   -0.010920
 2019-01-04   -0.003652
 2019-01-16   -0.005084
 2019-02-07   -0.009684
 2019-03-07   -0.012188
 2019-03-28   -0.007984
 2019-04-24   -0.010566
 2019-05-21   -0.003079
 2019-05-30   -0.005687
 2019-06-18   -0.005117
 2019-07-03   -0.009843
 2019-08-19   -0.011005
 2019-09-26   -0.011458
 2019-11-06    0.008923
 2019-11-25   -0.001101
 2019-12-23    0.001009
 2020-01-09   -0.008499
 2020-03-18    0.005308
 2020-04-03   -0.019941
 2020-04-22   -0.010321
 2020-05-12   -0.008992
 2020-05-14   -0.001448
 2020-06-17    0.028463
 2020-08-11    0.028833
 2020-10-19    0.002612
 2020-10-30   -0.015787
 2020-12-23    0.025290
 2021-03-02   -0.003710
 2021-05-05    0.011253
 2021-05-13   -0.005098
 2021-05-28   -0.002974
 2021-08-10   -0.012235
 2021-09-15    0.003937
 2021-11-08   -0.000626
 2021-11-11   -0.012581
 2022-01-21    0.001883
 2022-02-21   -0.012656
 Name: return, dtype: float64,
 Date
 2017-05-11    0.014104
 2017-05-31    0.007530
 2017-08-09    0.028341
 2017-09-04   -0.006340
 2017-09-13   -0.010392
 2017-10-25   -0.000780
 2017-10-27   -0.002728
 2017-12-08    0.008945
 2018-01-11    0.016076
 2018-02-06    0.009088
 2018-03-09    0.000062
 2018-03-16   -0.007639
 2018-03-30   -0.007671
 2018-04-23   -0.009916
 2018-06-20   -0.007965
 2018-07-30    0.000585
 2018-08-03   -0.010972
 2018-09-12    0.003476
 2018-10-01   -0.009656
 2018-10-18   -0.003975
 2018-11-13   -0.010920
 2019-01-04   -0.003652
 2019-01-17   -0.005707
 2019-02-07   -0.009684
 2019-03-07   -0.012188
 2019-03-28   -0.007984
 2019-04-24   -0.010566
 2019-05-21   -0.003079
 2019-05-30   -0.005687
 2019-06-18   -0.005117
 2019-07-03   -0.009843
 2019-08-19   -0.011005
 2019-09-26   -0.011458
 2019-11-06    0.008923
 2019-12-23    0.001009
 2020-01-09   -0.008499
 2020-03-18    0.005308
 2020-04-03   -0.019941
 2020-04-22   -0.010321
 2020-05-12   -0.008992
 2020-05-14   -0.001448
 2020-06-18    0.025351
 2020-08-11    0.028246
 2020-10-19    0.002612
 2020-10-30   -0.015787
 2020-12-24    0.024516
 2021-03-02   -0.003710
 2021-05-05    0.011253
 2021-05-14    0.000449
 2021-05-28   -0.002974
 2021-08-10   -0.012235
 2021-08-18   -0.000492
 2021-09-15    0.003937
 2021-11-08   -0.000626
 2021-11-11   -0.012581
 2022-01-21    0.001883
 2022-02-21   -0.012656
 Name: return, dtype: float64,
 Date
 2017-05-11    0.014256
 2017-05-31    0.007530
 2017-08-09    0.028341
 2017-09-04   -0.006340
 2017-09-13   -0.010392
 2017-10-25   -0.000780
 2017-10-27   -0.002728
 2017-12-07    0.009384
 2018-01-10    0.008715
 2018-02-06    0.009088
 2018-03-12    0.002505
 2018-03-16   -0.007639
 2018-03-30   -0.007671
 2018-04-23   -0.013335
 2018-06-20   -0.007965
 2018-07-30    0.000585
 2018-08-02   -0.008898
 2018-09-12    0.003476
 2018-10-01   -0.009656
 2018-10-18   -0.003975
 2018-11-13   -0.010920
 2019-01-04   -0.003652
 2019-01-16   -0.005084
 2019-02-07   -0.009684
 2019-03-07   -0.012188
 2019-03-28   -0.007984
 2019-04-24   -0.010566
 2019-05-21   -0.003079
 2019-05-30   -0.005687
 2019-06-18   -0.005117
 2019-07-03   -0.009843
 2019-08-19   -0.011005
 2019-09-26   -0.011458
 2019-11-06    0.008923
 2019-12-23    0.001009
 2020-01-09   -0.008499
 2020-03-18    0.005308
 2020-04-03   -0.019941
 2020-04-22   -0.010321
 2020-05-12   -0.008992
 2020-05-14   -0.001448
 2020-06-17    0.028463
 2020-08-11    0.028246
 2020-10-19    0.002612
 2020-10-30   -0.015787
 2020-12-23    0.025290
 2021-03-02   -0.003710
 2021-05-05    0.011253
 2021-05-13   -0.005098
 2021-05-28   -0.002974
 2021-08-10   -0.012235
 2021-09-15    0.003937
 2021-11-08   -0.000626
 2021-11-11   -0.012581
 2022-01-21    0.001883
 2022-02-21   -0.012656
 Name: return, dtype: float64,
 Date
 2017-05-11    0.014256
 2017-05-31    0.007530
 2017-08-09    0.028341
 2017-09-04   -0.006340
 2017-09-13   -0.010392
 2017-10-25   -0.000780
 2017-10-27   -0.002728
 2017-12-08    0.008945
 2018-01-11    0.016076
 2018-02-06    0.009088
 2018-03-09    0.000062
 2018-03-16   -0.007639
 2018-03-30   -0.007671
 2018-04-23   -0.009916
 2018-06-20   -0.007965
 2018-07-30    0.000585
 2018-08-02   -0.008898
 2018-09-12    0.003476
 2018-10-01   -0.009656
 2018-10-18   -0.003975
 2018-11-13   -0.010920
 2019-01-04   -0.003652
 2019-01-17   -0.005707
 2019-02-07   -0.009684
 2019-03-07   -0.012188
 2019-03-28   -0.007984
 2019-04-24   -0.010566
 2019-05-21   -0.003079
 2019-05-30   -0.005687
 2019-06-19   -0.001708
 2019-07-03   -0.009843
 2019-08-19   -0.011005
 2019-09-26   -0.011458
 2019-11-06    0.008923
 2019-12-24    0.000865
 2020-01-09   -0.008499
 2020-03-18    0.005308
 2020-04-03   -0.019941
 2020-04-22   -0.010321
 2020-05-12   -0.008992
 2020-05-14   -0.001448
 2020-06-18    0.025351
 2020-08-11    0.028246
 2020-10-19    0.002612
 2020-10-30   -0.015787
 2020-12-24    0.024516
 2021-03-02   -0.003710
 2021-05-05    0.011253
 2021-05-13   -0.005098
 2021-05-28   -0.002974
 2021-08-10   -0.012235
 2021-08-18   -0.000492
 2021-09-15    0.003937
 2021-11-08   -0.000626
 2021-11-11   -0.012581
 2022-01-21    0.001883
 2022-02-21   -0.012656
 Name: return, dtype: float64,
 Date
 2017-05-11    0.014256
 2017-05-31    0.007530
 2017-06-06    0.001093
 2017-08-09    0.028341
 2017-09-04   -0.006340
 2017-09-13   -0.010392
 2017-10-25   -0.000780
 2017-10-27   -0.002728
 2017-12-08    0.008945
 2018-01-11    0.016076
 2018-02-06    0.009088
 2018-03-09    0.000062
 2018-03-16   -0.007639
 2018-03-30   -0.007671
 2018-04-23   -0.009916
 2018-06-20   -0.007965
 2018-08-03   -0.012001
 2018-09-12    0.003476
 2018-10-01   -0.009656
 2018-11-13   -0.010920
 2019-01-04   -0.003652
 2019-01-17   -0.005707
 2019-02-07   -0.009684
 2019-03-07   -0.012188
 2019-03-28   -0.007984
 2019-04-24   -0.010566
 2019-05-21   -0.003079
 2019-05-30   -0.005687
 2019-06-19   -0.001708
 2019-07-03   -0.009843
 2019-08-19   -0.011005
 2019-09-26   -0.011458
 2019-11-06    0.008923
 2019-12-24    0.000865
 2020-01-09   -0.008499
 2020-03-18    0.005308
 2020-04-03   -0.019941
 2020-04-22   -0.010321
 2020-05-12   -0.008992
 2020-05-14   -0.001448
 2020-06-18    0.025351
 2020-08-11    0.028246
 2020-10-19    0.002612
 2020-10-30   -0.015787
 2020-12-24    0.024516
 2021-03-02   -0.003710
 2021-05-05    0.011253
 2021-05-14    0.000449
 2021-05-28   -0.002974
 2021-08-10   -0.012235
 2021-08-18   -0.000492
 2021-09-16   -0.000693
 2021-11-11   -0.012776
 2022-01-21    0.001883
 2022-02-21   -0.012656
 Name: return, dtype: float64,
 Date
 2017-05-11    0.014104
 2017-05-31    0.007530
 2017-06-06    0.001093
 2017-08-09    0.028341
 2017-09-04   -0.006340
 2017-09-13   -0.010392
 2017-10-25   -0.000780
 2017-10-27   -0.002728
 2017-12-08    0.008945
 2018-01-11    0.016076
 2018-02-06    0.009088
 2018-03-09    0.000062
 2018-03-16   -0.007639
 2018-03-30   -0.007671
 2018-04-23   -0.009916
 2018-06-20   -0.007965
 2018-08-03   -0.012001
 2018-10-01   -0.000753
 2018-11-13   -0.010252
 2019-01-04   -0.003652
 2019-01-17   -0.005707
 2019-02-07   -0.009684
 2019-03-07   -0.012188
 2019-03-28   -0.007984
 2019-04-24   -0.010566
 2019-05-21   -0.003079
 2019-05-30   -0.005687
 2019-06-19   -0.001708
 2019-07-03   -0.009843
 2019-08-19   -0.011005
 2019-09-26   -0.011458
 2019-11-06    0.008923
 2019-12-24    0.000787
 2020-01-09   -0.008499
 2020-03-18    0.005308
 2020-04-03   -0.019941
 2020-04-22   -0.010321
 2020-05-12   -0.008992
 2020-05-14   -0.001448
 2020-06-18    0.025351
 2020-08-11    0.028246
 2020-10-19    0.002612
 2020-10-30   -0.015787
 2020-12-24    0.024516
 2021-03-02   -0.003710
 2021-05-05    0.011253
 2021-05-14    0.000449
 2021-05-28   -0.002974
 2021-08-10   -0.012235
 2021-08-18   -0.000492
 2021-09-17   -0.003752
 2021-11-11   -0.012776
 2022-01-21    0.001883
 2022-02-21   -0.012656
 Name: return, dtype: float64,
 Date
 2017-05-11    0.014256
 2017-05-31    0.007530
 2017-08-09    0.028341
 2017-09-04   -0.006340
 2017-09-13   -0.010392
 2017-10-25   -0.000780
 2017-10-27   -0.002728
 2017-12-08    0.008945
 2018-01-11    0.016076
 2018-02-06    0.009088
 2018-03-09    0.000062
 2018-03-16   -0.007639
 2018-03-30   -0.007671
 2018-04-23   -0.009916
 2018-06-20   -0.007965
 2018-07-30    0.000585
 2018-08-03   -0.010972
 2018-09-12    0.003476
 2018-10-01   -0.009656
 2018-11-13   -0.010920
 2019-01-04   -0.003652
 2019-01-17   -0.005707
 2019-02-07   -0.009684
 2019-03-07   -0.012188
 2019-03-28   -0.007984
 2019-04-24   -0.010566
 2019-05-21   -0.003079
 2019-05-30   -0.005687
 2019-06-19   -0.001708
 2019-07-03   -0.009843
 2019-08-19   -0.011005
 2019-09-26   -0.011458
 2019-11-06    0.008923
 2019-12-24    0.000865
 2020-01-09   -0.008499
 2020-03-18    0.005308
 2020-04-03   -0.019941
 2020-04-22   -0.010321
 2020-05-12   -0.008992
 2020-05-14   -0.001448
 2020-06-18    0.025351
 2020-08-11    0.028246
 2020-10-19    0.002612
 2020-10-30   -0.015787
 2020-12-24    0.024516
 2021-03-03   -0.006735
 2021-05-05    0.011253
 2021-05-14    0.000449
 2021-05-28   -0.002974
 2021-08-10   -0.012235
 2021-08-18   -0.000492
 2021-09-16   -0.000693
 2021-11-11   -0.012776
 2022-01-21    0.001883
 2022-02-21   -0.012656
 Name: return, dtype: float64,
 Date
 2017-05-11    0.014256
 2017-05-31    0.007530
 2017-06-06    0.001093
 2017-08-09    0.028341
 2017-09-04   -0.006340
 2017-09-13   -0.010392
 2017-10-25   -0.000780
 2017-10-27   -0.002728
 2017-12-08    0.008945
 2018-01-11    0.016076
 2018-02-06    0.009088
 2018-03-09    0.000062
 2018-03-16   -0.007639
 2018-03-30   -0.007671
 2018-04-23   -0.009916
 2018-06-20   -0.007965
 2018-08-03   -0.012001
 2018-10-01   -0.000753
 2018-11-13   -0.010252
 2019-01-04   -0.003652
 2019-01-17   -0.005707
 2019-02-07   -0.009684
 2019-03-07   -0.012188
 2019-03-28   -0.007984
 2019-04-24   -0.010566
 2019-05-21   -0.003079
 2019-05-30   -0.005687
 2019-06-19   -0.001708
 2019-07-03   -0.009843
 2019-08-19   -0.011005
 2019-09-26   -0.011458
 2019-11-06    0.008923
 2019-12-24    0.000787
 2020-01-09   -0.008499
 2020-03-18    0.005308
 2020-04-03   -0.019941
 2020-04-22   -0.010321
 2020-05-12   -0.008992
 2020-05-15   -0.000227
 2020-06-18    0.025351
 2020-08-11    0.028246
 2020-10-19    0.002612
 2020-10-30   -0.015787
 2020-12-24    0.024516
 2021-03-03   -0.006735
 2021-05-05    0.011253
 2021-05-14    0.000449
 2021-05-28   -0.002974
 2021-08-10   -0.012235
 2021-08-18   -0.000492
 2021-09-17   -0.003752
 2021-11-11   -0.012776
 2022-01-21    0.001883
 2022-02-21   -0.012656
 Name: return, dtype: float64,
 Date
 2017-05-11    0.014256
 2017-05-31    0.007530
 2017-06-02    0.005548
 2017-06-06    0.001093
 2017-08-09    0.028341
 2017-09-04   -0.006340
 2017-09-13   -0.010392
 2017-10-25    0.000603
 2017-10-27   -0.002728
 2017-12-08    0.008945
 2018-01-11    0.016076
 2018-02-06    0.009088
 2018-03-09    0.000062
 2018-03-16   -0.007639
 2018-03-30   -0.007671
 2018-04-23   -0.009916
 2018-06-21   -0.008102
 2018-08-03   -0.012001
 2018-10-01   -0.000753
 2018-11-13   -0.010252
 2019-01-17   -0.005491
 2019-02-07   -0.009684
 2019-03-07   -0.012188
 2019-03-28   -0.009354
 2019-04-24   -0.010566
 2019-05-21   -0.003782
 2019-05-30   -0.005687
 2019-06-19   -0.001708
 2019-07-03   -0.009843
 2019-08-19   -0.011005
 2019-09-26   -0.011458
 2019-11-06    0.008923
 2019-12-24    0.000787
 2020-01-09   -0.008499
 2020-03-18    0.005308
 2020-04-03   -0.019941
 2020-04-22   -0.010321
 2020-05-12   -0.008992
 2020-05-15   -0.000227
 2020-06-18    0.025351
 2020-08-11    0.028246
 2020-10-19    0.002612
 2020-10-30   -0.015787
 2020-12-24    0.030571
 2021-03-03   -0.006735
 2021-05-06    0.016036
 2021-05-14    0.000449
 2021-05-28   -0.002974
 2021-08-10   -0.004641
 2021-08-18   -0.000492
 2021-09-17   -0.003752
 2021-11-11   -0.012776
 2022-01-21    0.001883
 2022-02-21   -0.012656
 Name: return, dtype: float64,
 Date
 2017-05-11    0.014256
 2017-05-31    0.007530
 2017-06-02    0.005548
 2017-06-06    0.001093
 2017-08-09    0.028341
 2017-09-04   -0.006340
 2017-09-13   -0.010392
 2017-10-25    0.000603
 2017-10-27   -0.002728
 2017-12-08    0.008945
 2018-01-11    0.016076
 2018-02-06    0.015452
 2018-03-09    0.000062
 2018-03-16   -0.007639
 2018-03-30   -0.007671
 2018-04-23   -0.009916
 2018-06-21   -0.008102
 2018-08-03   -0.012001
 2018-10-01   -0.000753
 2018-11-13   -0.010252
 2019-01-17   -0.005491
 2019-02-07   -0.009684
 2019-03-07   -0.012188
 2019-03-28   -0.009354
 2019-04-24   -0.010566
 2019-05-21   -0.003782
 2019-05-30   -0.005687
 2019-06-19   -0.001708
 2019-07-03   -0.009843
 2019-08-19   -0.011005
 2019-09-26   -0.011458
 2019-11-06    0.008923
 2019-12-24    0.000787
 2020-01-09   -0.008499
 2020-03-18    0.005308
 2020-04-03   -0.019941
 2020-04-22   -0.015983
 2020-05-12   -0.008992
 2020-05-15   -0.000227
 2020-06-18    0.025351
 2020-08-11    0.028246
 2020-10-19    0.000212
 2020-10-30   -0.015787
 2020-12-24    0.030571
 2021-03-03   -0.006735
 2021-05-06    0.016036
 2021-05-14    0.000449
 2021-05-28    0.002865
 2021-07-14    0.005006
 2021-08-10   -0.007899
 2021-08-18   -0.000492
 2021-09-17   -0.003752
 2021-11-11   -0.014356
 2022-01-21    0.001883
 2022-02-21   -0.012656
 Name: return, dtype: float64,
 Date
 2017-05-11    0.014256
 2017-05-31    0.007530
 2017-06-06    0.001093
 2017-08-09    0.028341
 2017-09-04   -0.006340
 2017-09-13   -0.010392
 2017-10-25    0.000603
 2017-10-27   -0.002728
 2017-12-08    0.008945
 2018-01-11    0.016076
 2018-02-06    0.009088
 2018-03-09    0.000062
 2018-03-16   -0.007639
 2018-03-30   -0.007671
 2018-04-23   -0.009916
 2018-06-21   -0.005397
 2018-08-03   -0.012001
 2018-10-01   -0.000753
 2018-11-13   -0.010252
 2019-01-07    0.002147
 2019-01-17   -0.005707
 2019-02-07   -0.009684
 2019-03-07   -0.012188
 2019-03-28   -0.009354
 2019-04-24   -0.010566
 2019-05-21   -0.003782
 2019-05-30   -0.005687
 2019-06-19   -0.001708
 2019-07-03   -0.009843
 2019-08-19   -0.011005
 2019-09-26   -0.011458
 2019-11-06    0.008923
 2019-12-24    0.000787
 2020-01-09   -0.008499
 2020-03-18    0.005308
 2020-04-03   -0.019941
 2020-04-22   -0.010321
 2020-05-12   -0.008992
 2020-05-15   -0.000227
 2020-06-18    0.025351
 2020-08-11    0.028246
 2020-10-19    0.002612
 2020-10-30   -0.015787
 2020-12-24    0.030571
 2021-03-03   -0.006735
 2021-05-06    0.016036
 2021-05-14    0.000449
 2021-05-28   -0.002974
 2021-08-10   -0.012235
 2021-08-18   -0.000492
 2021-09-17   -0.003752
 2021-11-11   -0.012776
 2022-01-21    0.001883
 2022-02-21   -0.012656
 Name: return, dtype: float64,
 Date
 2017-05-11    0.014256
 2017-05-31    0.007530
 2017-06-02    0.005548
 2017-06-06    0.001093
 2017-08-09    0.028341
 2017-09-04   -0.006340
 2017-09-13   -0.010392
 2017-10-25    0.000603
 2017-10-27   -0.002728
 2017-12-08    0.008945
 2018-01-11    0.016076
 2018-02-06    0.015452
 2018-03-09    0.000062
 2018-03-16   -0.007639
 2018-03-30   -0.007671
 2018-04-23   -0.009916
 2018-06-21   -0.008102
 2018-08-03   -0.012001
 2018-10-01   -0.000753
 2018-11-13   -0.010252
 2019-01-17   -0.005491
 2019-02-07   -0.009684
 2019-03-07   -0.012188
 2019-03-28   -0.009354
 2019-04-25   -0.012329
 2019-05-21   -0.003782
 2019-05-30   -0.005687
 2019-06-19   -0.001708
 2019-07-03   -0.009843
 2019-08-19   -0.011005
 2019-09-26   -0.011458
 2019-11-06    0.008923
 2019-12-24    0.000787
 2020-01-09   -0.008499
 2020-03-18    0.005308
 2020-04-03   -0.013035
 2020-04-22   -0.015983
 2020-05-12   -0.008992
 2020-05-15   -0.000227
 2020-06-18    0.025351
 2020-08-11    0.028246
 2020-10-19    0.000212
 2020-10-30   -0.015787
 2020-12-24    0.030571
 2021-03-03   -0.006735
 2021-05-06    0.016036
 2021-05-14    0.000449
 2021-05-28   -0.002974
 2021-07-14    0.005006
 2021-08-11   -0.006012
 2021-08-18   -0.000492
 2021-09-17   -0.003752
 2021-11-11   -0.014356
 2022-01-21    0.001883
 2022-02-21   -0.012656
 Name: return, dtype: float64,
 Date
 2017-05-11    0.014256
 2017-05-31    0.007530
 2017-06-02    0.005548
 2017-06-07   -0.000315
 2017-08-09    0.028341
 2017-09-04   -0.006340
 2017-09-13   -0.010392
 2017-10-25    0.000603
 2017-10-27   -0.002728
 2017-12-08   -0.001907
 2018-01-11    0.016076
 2018-02-06    0.015452
 2018-03-09    0.000062
 2018-03-16   -0.002186
 2018-03-30   -0.007671
 2018-04-23   -0.009916
 2018-06-21   -0.008102
 2018-08-03   -0.012001
 2018-10-01   -0.000753
 2018-11-13   -0.010252
 2019-01-17   -0.005491
 2019-02-07   -0.009684
 2019-03-07   -0.014451
 2019-03-28   -0.009354
 2019-04-25   -0.010859
 2019-05-21   -0.003782
 2019-05-30   -0.005687
 2019-06-19   -0.001708
 2019-07-03   -0.009843
 2019-08-19   -0.010916
 2019-09-26   -0.008291

In [75]:
trades_summary

            TS_Trends  TS_Trades  TS_Entries  TS_Exits  action_price    return
Date
2017-05-11      False         -1       False      True      1.086602  0.014256
2017-06-02      False         -1       False      True      1.127548  0.010870
2017-06-07      False         -1       False      True      1.125467 -0.000315
2017-08-09      False         -1       False      True      1.176471  0.028341
2017-09-04      False         -1       False      True      1.189443 -0.006340
2017-09-13      False         -1       False      True      1.189047 -0.010392
2017-10-24      False         -1       False      True      1.175986 -0.004669
2017-10-27      False         -1       False      True      1.160726 -0.002728
2017-12-08      False         -1       False      True      1.176928 -0.001907
2018-01-11      False         -1       False      True      1.204210  0.016076
2018-02-07      False         -1       False      True      1.226843  0.006183
2018-03-16      False         -1       False      True      1.228079 -0.002186
2018-03-30      False         -1       False      True      1.231284 -0.007671
2018-04-23      False         -1       False      True      1.221120 -0.009916
2018-06-21      False         -1       False      True      1.160699 -0.008102
2018-08-03      False         -1       False      True      1.156136 -0.012001
2018-10-01      False         -1       False      True      1.157756 -0.000753
2018-11-13      False         -1       False      True      1.131606 -0.010252
2019-01-17      False         -1       False      True      1.139186 -0.005491
2019-02-07      False         -1       False      True      1.133993 -0.009684
2019-03-07      False         -1       False      True      1.120197 -0.014451
2019-03-28      False         -1       False      True      1.122952 -0.009354
2019-04-25      False         -1       False      True      1.113710 -0.010859
2019-05-21      False         -1       False      True      1.115511 -0.003782
2019-05-30      False         -1       False      True      1.112991 -0.005687
2019-06-19      False         -1       False      True      1.123583 -0.001708
2019-07-03      False         -1       False      True      1.128796 -0.008353
2019-08-19      False         -1       False      True      1.108254 -0.010916
2019-09-26      False         -1       False      True      1.092311 -0.008291
2019-11-06      False         -1       False      True      1.107064  0.008923
2019-12-24      False         -1       False      True      1.109139  0.000787
2020-01-09      False         -1       False      True      1.110926 -0.008499
2020-03-18      False         -1       False      True      1.094343  0.005308
2020-04-03      False         -1       False      True      1.080824 -0.013035
2020-04-21      False         -1       False      True      1.085741 -0.011379
2020-05-12      False         -1       False      True      1.084634 -0.008992
2020-05-15      False         -1       False      True      1.081947 -0.000227
2020-06-18      False         -1       False      True      1.120724  0.025351
2020-08-11      False         -1       False      True      1.173985  0.028246
2020-10-19      False         -1       False      True      1.176803  0.000082
2020-10-30      False         -1       False      True      1.164253 -0.015787
2020-12-24      False         -1       False      True      1.218472  0.030571
2021-03-03      False         -1       False      True      1.204834 -0.006000
2021-05-06      False         -1       False      True      1.206593  0.016337
2021-05-14      False         -1       False      True      1.214757  0.000449
2021-05-31      False         -1       False      True      1.223406  0.006484
2021-07-14      False         -1       False      True      1.183334  0.005006
2021-08-11      False         -1       False      True      1.174205 -0.006012
2021-08-18      False         -1       False      True      1.170385 -0.000492
2021-09-17      False         -1       False      True      1.172883 -0.003752
2021-11-11      False         -1       False      True      1.144780 -0.014356
2022-01-21      False         -1       False      True      1.134095  0.003017
2022-02-21      False         -1       False      True      1.130966 -0.012656

In [77]:
result = pd.DataFrame(compare, columns=['Avg Return', 'Median', 'Worst Trade Return', 'MACD Parameter Set'])
result

    Avg Return    Median  Worst Trade Return MACD Parameter Set
0    -0.001542 -0.003652           -0.019941           (11, 21)
1    -0.001765 -0.003843           -0.019941           (11, 22)
2    -0.001805 -0.003975           -0.019941           (11, 23)
3    -0.001640 -0.003710           -0.019941           (11, 24)
4    -0.001781 -0.004529           -0.019941           (12, 21)
5    -0.001641 -0.003710           -0.019941           (12, 22)
6    -0.001651 -0.003652           -0.019941           (12, 23)
7    -0.001630 -0.003681           -0.019941           (12, 24)
8    -0.001697 -0.003652           -0.019941           (13, 21)
9    -0.001660 -0.003702           -0.019941           (13, 22)
10   -0.001160 -0.003767           -0.019941           (13, 23)
11   -0.001061 -0.003752           -0.019941           (13, 24)
12   -0.001318 -0.003767           -0.019941           (14, 21)
13   -0.001039 -0.003752           -0.015983           (14, 22)
14   -0.000935 -0.002728           -0.015983           (14, 23)
15   -0.001145 -0.003782           -0.015787           (14, 24)

In [79]:
result = pd.DataFrame(compare, columns=['Avg Return', 'Median', 'Worst Trade Return', 'MACD Parameter Set']).set_index('MACD Parameter Set', drop=True)
result

                    Avg Return    Median  Worst Trade Return
MACD Parameter Set
(11, 21)             -0.001542 -0.003652           -0.019941
(11, 22)             -0.001765 -0.003843           -0.019941
(11, 23)             -0.001805 -0.003975           -0.019941
(11, 24)             -0.001640 -0.003710           -0.019941
(12, 21)             -0.001781 -0.004529           -0.019941
(12, 22)             -0.001641 -0.003710           -0.019941
(12, 23)             -0.001651 -0.003652           -0.019941
(12, 24)             -0.001630 -0.003681           -0.019941
(13, 21)             -0.001697 -0.003652           -0.019941
(13, 22)             -0.001660 -0.003702           -0.019941
(13, 23)             -0.001160 -0.003767           -0.019941
(13, 24)             -0.001061 -0.003752           -0.019941
(14, 21)             -0.001318 -0.003767           -0.019941
(14, 22)             -0.001039 -0.003752           -0.015983
(14, 23)             -0.000935 -0.002728           -0.015983
(14, 24)             -0.001145 -0.003782           -0.015787

In [80]:
result[result['Median'] == result['Median'].max()]

                    Avg Return    Median  Worst Trade Return
MACD Parameter Set
(14, 23)             -0.000935 -0.002728           -0.015983