In [5]:
# Basic  function
def is_even(n):
  return n % 2 == 0
  
#แปลงฟังก์ชั่นข้างบนให้อยู่ในรูป Lambda Function 
is_even = lambda x: x % 2 == 0
print(is_even(12))

True

In [18]:
import pandas as pd

data = {'ID' : ['A', 'B', 'C', 'D'], 'Math':[91, 75, 62, 80], 'Science':[66, 70, 75, 77]}
df = pd.DataFrame(data)

# ใช้ apply lambda function เพื่อแยกคนที่ได้คะแนน Math เกิน 80 ให้ print คำว่า pass ส่วนที่เหลือให้ print fail
a = df.apply(lambda x: 'pass' if x.Math > 80 else 'fail', axis=1)
print(a)


# ใช้ apply lambda function เพื่อแยกคนที่ได้คะแนน Math มากกว่าเท่ากับ 80 และคะแนน Science เกิน 70 ให้ print คำว่า pass ส่วนที่เหลือให้ print fail
b = df.apply(lambda x: 'pass' if x.Math >= 80 and x.Science > 70 else 'fail', axis=1)
print(b)

0    pass
1    fail
2    fail
3    fail
dtype: object
0    fail
1    fail
2    fail
3    pass
dtype: object