In [40]:
import pandas as pd
import numpy as np

In [41]:
path = ".\data\stock-siamchart.xlsx"

In [42]:
df = pd.read_excel(path)

In [43]:
df

,Name,No.,Links,Sign,Last,Chg%,Volume,Value (k),MCap (M),P/E,...,ROA%,ROE%,NPM%,Yield%,FFloat%,MG%,Magic1,Magic2,PEG,CG
0,Average,NaN,NaN,NaN,19.49,1.61,3.363165e+07,105048.26,24834.05,62.50,...,5.61,2.36,-12.97,0.77,40.89,NaN,559.69,558.51,-1.10,NaN
1,2S,1.0,i | 1 | 2 | 3,NaN,6.85,2.24,1.073600e+06,7281.00,3425.00,4.72,...,40.31,38.98,15.65,3.28,58.11,NaN,31.00,17.00,0.02,NaN
2,3K-BAT,2.0,i,NaN,68.25,-0.73,1.000000e+03,68.00,5351.00,49.35,...,-3.08,5.28,3.29,0.37,2.10,NaN,914.00,NaN,NaN,NaN
3,7UP,3.0,i | 1 | 2 | 3,NaN,1.61,2.55,2.758150e+08,440191.00,8280.00,39.60,...,7.70,10.20,37.44,NaN,66.55,NaN,741.00,713.00,-0.29,NaN
4,A,4.0,i | 1 | 2 | 3,NaN,4.96,-0.40,1.500000e+03,7.00,4861.00,51.30,...,3.99,2.77,-4.93,0.60,25.86,NaN,989.00,927.00,-0.18,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
752,XPG,752.0,i | 1 | 2 | 3,NaN,3.98,-4.33,3.193370e+07,128129.00,11405.00,830.92,...,1.49,1.56,129.78,NaN,61.26,NaN,1082.00,1106.00,-1.65,NaN
753,YGG,753.0,i | 1 | 3,NaN,20.70,-1.90,6.996000e+05,14600.00,3726.00,43.20,...,22.08,24.21,32.10,0.85,26.32,NaN,534.00,489.00,2.63,NaN
754,YUASA,754.0,i | 1 | 3,NaN,16.80,0.00,6.400000e+03,108.00,1808.00,10.59,...,16.70,20.39,5.82,2.63,15.27,NaN,215.00,178.00,0.23,NaN
755,ZEN,755.0,i | 1 | 3,NaN,11.80,-0.84,1.912000e+05,2278.00,3540.00,158.12,...,2.18,1.83,-3.45,2.12,26.68,NaN,1060.00,1060.00,-6.52,NaN
756,ZIGA,756.0,i | 1 | 2 | 3,NaN,5.05,-1.94,5.696200e+06,29052.00,2511.00,16.18,...,14.36,20.29,13.69,3.19,37.17,NaN,322.00,306.00,0.32,NaN

In [44]:
# df[(df['P/E'] > 10) & 
# (df['P/E'] < 25) &
# (df['P/BV'] < 1)].sort_values(['P/E', 'ROE%'], ascending=[True, False]) # There is '-' in 'P/BV'

In [45]:
df[df['P/BV'] == '-']

,Name,No.,Links,Sign,Last,Chg%,Volume,Value (k),MCap (M),P/E,...,ROA%,ROE%,NPM%,Yield%,FFloat%,MG%,Magic1,Magic2,PEG,CG
40,AMR,40.0,i,NaN,6.65,0.76,5043200.0,33595.0,0.0,NaN,...,18.84,54.93,10.90,-,37.78,NaN,NaN,NaN,NaN,NaN
164,CV,164.0,i,NaN,3.90,0.52,143669700.0,566762.0,0.0,NaN,...,9.74,14.31,6.42,-,46.30,NaN,NaN,NaN,NaN,NaN
351,MENA,351.0,i,NaN,2.04,0.00,136090200.0,286553.0,0.0,NaN,...,6.00,6.58,7.25,-,41.30,NaN,NaN,NaN,NaN,NaN
526,SECURE,526.0,i,NaN,24.70,0.41,681800.0,16816.0,0.0,NaN,...,9.33,10.46,9.50,-,28.41,NaN,NaN,NaN,NaN,NaN
559,SNNP,559.0,i,NaN,12.60,-2.33,10101300.0,128670.0,0.0,NaN,...,10.72,60.85,11.27,-,28.50,NaN,NaN,NaN,NaN,NaN
588,STECH,588.0,i,NaN,2.60,0.78,3758600.0,9764.0,0.0,NaN,...,8.80,20.21,6.96,-,38.67,NaN,NaN,NaN,NaN,NaN

In [46]:
df = df.replace('-', np.nan)

In [47]:
df[df['P/BV'] == '-']

Empty DataFrame
Columns: [Name, No., Links, Sign, Last, Chg%, Volume, Value (k), MCap (M), P/E, P/BV, D/E, DPS, EPS, ROA%, ROE%, NPM%, Yield%, FFloat%, MG%, Magic1, Magic2, PEG, CG]
Index: []

[0 rows x 24 columns]

In [48]:
df.dtypes

Name          object
No.          float64
Links         object
Sign          object
Last         float64
Chg%         float64
Volume       float64
Value (k)    float64
MCap (M)     float64
P/E          float64
P/BV          object
D/E          float64
DPS           object
EPS          float64
ROA%         float64
ROE%         float64
NPM%         float64
Yield%        object
FFloat%      float64
MG%          float64
Magic1       float64
Magic2       float64
PEG          float64
CG           float64
dtype: object

In [49]:
df['P/BV'] = df['P/BV'].astype(float)
df['Yield%'] = df['Yield%'].astype(float)

In [50]:
df.dtypes

Name          object
No.          float64
Links         object
Sign          object
Last         float64
Chg%         float64
Volume       float64
Value (k)    float64
MCap (M)     float64
P/E          float64
P/BV         float64
D/E          float64
DPS           object
EPS          float64
ROA%         float64
ROE%         float64
NPM%         float64
Yield%       float64
FFloat%      float64
MG%          float64
Magic1       float64
Magic2       float64
PEG          float64
CG           float64
dtype: object

In [52]:
df[(df['P/E'] > 10) & 
(df['P/E'] < 25) &
(df['P/BV'] < 1)].sort_values(['P/E', 'ROE%'], ascending=[True, False])

,Name,No.,Links,Sign,Last,Chg%,Volume,Value (k),MCap (M),P/E,...,ROA%,ROE%,NPM%,Yield%,FFloat%,MG%,Magic1,Magic2,PEG,CG
159,CSC,159.0,i | 1 | 3,NaN,48.75,-0.51,46000.0,2247.0,2535.0,10.13,...,6.99,7.02,8.05,5.03,38.07,NaN,488.0,397.0,1.18,NaN
597,SUSCO,597.0,i | 1 | 2 | 3,NaN,3.32,0.61,1608800.0,5345.0,3652.0,10.18,...,7.69,9.45,1.70,3.34,54.87,NaN,411.0,363.0,0.32,NaN
96,BKI,96.0,i | 1 | 2 | 3,NaN,270.00,-0.37,17100.0,4623.0,28747.0,10.25,...,5.67,9.15,18.58,5.56,84.28,NaN,428.0,471.0,3.41,NaN
349,MDX,349.0,i | 1 | 3,NaN,6.15,3.36,6655900.0,40450.0,2925.0,10.31,...,8.01,10.51,207.55,NaN,76.69,NaN,366.0,339.0,0.18,NaN
79,BCP,79.0,i | 1 | 2 | 3,NaN,27.25,0.93,10457800.0,285228.0,37521.0,10.32,...,5.26,7.67,5.53,1.47,64.27,NaN,465.0,494.0,-0.79,NaN
223,GJS,223.0,i | 1 | 2 | 3,NaN,0.38,11.76,426575200.0,156050.0,9685.0,10.37,...,7.52,7.24,12.87,NaN,30.71,NaN,474.0,370.0,NaN,NaN
672,TPIPL,672.0,i | 1 | 2 | 3,NaN,1.80,0.56,18306200.0,33085.0,34428.0,10.39,...,5.59,7.56,17.78,3.30,38.10,NaN,471.0,476.0,0.39,NaN
253,IFS,253.0,i | 1 | 3,NaN,2.58,0.00,856100.0,2198.0,1273.0,10.47,...,5.59,8.16,37.82,5.43,26.81,NaN,458.0,486.0,1.56,NaN
439,PMTA,439.0,i | 1 | 2 | 3,NaN,11.50,0.00,31700.0,366.0,1164.0,10.67,...,7.41,7.42,3.24,6.09,14.61,NaN,489.0,396.0,-0.57,NaN
688,TSE,688.0,i | 1 | 2 | 3,NaN,2.82,0.00,9285800.0,26121.0,5972.0,10.72,...,4.90,9.23,48.31,1.77,39.72,NaN,439.0,533.0,0.16,NaN
296,KCAR,296.0,i | 1 | 2 | 3,NaN,8.55,-1.16,89000.0,761.0,2138.0,10.79,...,5.05,9.40,8.40,5.15,26.50,NaN,437.0,525.0,1.59,NaN
614,TCAP,614.0,i | 1 | 2 | 3,NaN,36.50,0.00,7088700.0,257988.0,42527.0,10.84,...,4.90,5.53,37.04,8.22,75.29,NaN,556.0,540.0,0.57,NaN
520,SCP,520.0,i | 1 | 2 | 3,NaN,5.90,-0.84,115000.0,679.0,1770.0,10.96,...,8.45,7.73,7.82,6.44,49.92,NaN,487.0,369.0,-2.18,NaN
76,BBL,76.0,i | 1 | 2 | 3,NaN,114.00,0.00,6231000.0,708242.0,217608.0,11.05,...,1.45,4.35,20.92,2.19,98.53,NaN,596.0,688.0,8.44,NaN
180,DTCI,180.0,i | 1 | 3,NaN,28.75,0.00,0.0,0.0,288.0,11.11,...,6.49,6.96,12.08,1.39,26.70,NaN,520.0,451.0,-0.87,NaN
68,AYUD,68.0,i | 1 | 2 | 3,NaN,37.00,-1.99,2500.0,93.0,14403.0,11.16,...,4.47,7.49,31.08,4.11,28.17,NaN,502.0,563.0,-0.96,NaN
364,ML,364.0,i | 1 | 2 | 3,NaN,1.35,7.14,20093800.0,26913.0,1437.0,11.19,...,6.74,6.44,25.92,3.70,43.40,NaN,541.0,448.0,-27.90,NaN
645,TK,645.0,i | 1 | 2 | 3,NaN,9.75,0.00,122400.0,1187.0,4875.0,11.26,...,8.35,8.19,20.96,4.31,24.48,NaN,480.0,382.0,1.81,NaN
461,PSH,461.0,i | 1 | 2 | 3,NaN,12.80,0.00,1148500.0,14762.0,28013.0,11.45,...,4.79,5.81,7.94,7.50,28.16,NaN,555.0,553.0,-3.87,NaN
472,QH,472.0,i | 1 | 2 | 3,NaN,2.22,0.91,35597300.0,78713.0,23786.0,11.50,...,5.65,7.87,21.42,5.41,74.86,NaN,496.0,508.0,-12.81,NaN
568,SPC,568.0,i | 1 | 2 | 3,NaN,59.25,-0.42,17500.0,1041.0,19553.0,11.64,...,6.48,7.33,5.36,2.70,38.01,NaN,514.0,462.0,2.15,NaN
139,CMC,139.0,i | 1 | 3,NaN,1.64,13.10,123293500.0,196492.0,1687.0,11.69,...,3.86,5.25,10.74,0.19,35.23,NaN,589.0,605.0,-0.14,NaN
580,SSSC,580.0,i | 1 | 3,NaN,2.76,-1.43,189000.0,524.0,1766.0,11.92,...,5.55,5.28,4.34,3.84,42.32,NaN,581.0,522.0,-1.45,NaN
601,SVOA,601.0,i | 1 | 2 | 3,NaN,2.00,2.04,18109600.0,36017.0,1414.0,12.16,...,4.10,7.01,1.72,2.50,63.56,NaN,536.0,588.0,0.56,NaN
330,LPN,330.0,i | 1 | 2 | 3,NaN,5.00,0.40,6754900.0,33735.0,7378.0,12.33,...,3.81,5.14,8.72,28.00,92.08,NaN,599.0,614.0,-1.22,NaN
512,SCB,512.0,i | 1 | 2 | 3,XD,104.00,-1.89,3662300.0,381120.0,353146.0,12.40,...,1.70,6.91,25.34,2.21,76.61,NaN,549.0,705.0,-3.38,NaN
695,TTB,695.0,i | 1 | 2 | 3,NaN,1.06,-0.93,111503500.0,118292.0,102194.0,12.51,...,1.35,4.01,16.24,4.25,34.20,NaN,640.0,725.0,-4.79,NaN
163,CTW,163.0,i | 1 | 2 | 3,NaN,8.05,0.63,62200.0,498.0,3203.0,12.67,...,5.57,5.85,0.58,5.59,25.95,NaN,586.0,544.0,-0.11,NaN
666,TOPP,666.0,i | 1 | 3,NaN,205.00,0.00,0.0,0.0,1230.0,12.86,...,6.10,6.77,6.63,3.33,22.69,NaN,565.0,518.0,1.74,NaN
571,SPI,571.0,i | 1 | 2 | 3,NaN,61.25,-0.41,200.0,12.0,35028.0,12.98,...,5.83,7.07,102.51,1.14,58.80,NaN,548.0,529.0,0.73,NaN
18,AFC,18.0,i | 1 | 3,NaN,12.20,5.17,130700.0,1605.0,556.0,14.14,...,2.82,3.47,5.23,NaN,43.31,NaN,681.0,681.0,-0.09,NaN
322,LEE,322.0,i | 1 | 2 | 3,NaN,2.74,0.74,473500.0,1296.0,2527.0,14.49,...,7.22,6.73,3.43,6.57,47.46,NaN,592.0,483.0,0.79,NaN
325,LHFG,325.0,i | 1 | 2 | 3,NaN,1.22,0.00,75746700.0,93753.0,25844.0,14.66,...,1.83,4.57,28.35,3.28,16.83,NaN,655.0,738.0,1.27,NaN
605,SYNTEC,605.0,i | 1 | 2 | 3,NaN,2.00,1.01,5411600.0,10878.0,3200.0,15.42,...,2.54,3.68,1.93,4.00,66.55,NaN,703.0,724.0,-1.57,NaN
190,EGCO,190.0,i | 1 | 2 | 3,NaN,181.00,0.84,1185100.0,214379.0,95290.0,15.49,...,5.31,5.97,12.44,3.59,50.00,NaN,629.0,606.0,0.35,NaN
395,NPK,395.0,i | 1 | 3,NaN,14.10,0.00,0.0,0.0,141.0,15.95,...,2.10,2.07,-2.59,0.72,23.39,NaN,744.0,752.0,-3.19,NaN
151,CPL,151.0,i | 1 | 2 | 3,NaN,2.04,2.00,634700.0,1298.0,897.0,16.14,...,3.46,5.69,6.83,0.98,28.69,NaN,653.0,700.0,-0.04,NaN
433,PL,433.0,i | 1 | 2 | 3,NaN,2.64,0.76,38000.0,100.0,1575.0,16.38,...,2.59,3.18,4.07,3.03,62.45,NaN,736.0,746.0,-1.69,NaN
692,TSTE,692.0,i | 1 | 2 | 3,NaN,7.10,1.43,8400.0,59.0,2722.0,16.40,...,5.33,5.01,11.32,2.46,25.77,NaN,689.0,627.0,2.39,NaN
533,SGF,533.0,i | 1 | 2 | 3,NaN,1.16,2.65,11117300.0,12665.0,1520.0,16.48,...,6.41,5.91,17.88,NaN,85.86,NaN,629.0,538.0,0.14,NaN
201,F&D,201.0,i | 1 | 3,NaN,24.40,0.00,300.0,7.0,430.0,16.83,...,2.07,2.37,5.06,NaN,24.82,NaN,760.0,775.0,0.06,NaN
107,BSBM,107.0,i | 1 | 2 | 3,NaN,1.45,0.69,1484000.0,2148.0,1626.0,16.85,...,6.12,5.10,7.01,5.52,31.10,NaN,680.0,582.0,-0.20,NaN
197,ESTAR,197.0,i | 1 | 3,NaN,0.58,1.75,40045900.0,23132.0,2913.0,16.90,...,3.40,3.73,2.59,1.72,39.65,NaN,728.0,714.0,2.45,NaN
280,JCT,280.0,i | 1 | 2 | 3,NaN,78.75,0.00,0.0,0.0,1063.0,17.43,...,5.53,5.23,7.21,4.47,25.46,NaN,692.0,631.0,-27.67,NaN
50,AQUA,50.0,i | 1 | 3,NaN,0.48,14.29,309327800.0,141079.0,2205.0,17.92,...,2.53,2.81,7.24,2.08,79.13,NaN,765.0,770.0,0.64,NaN
97,BLA,97.0,i | 1 | 2 | 3,NaN,26.75,0.00,1478200.0,39399.0,45677.0,18.19,...,0.84,5.38,7.29,0.86,44.59,NaN,691.0,839.0,3.59,NaN
123,CGH,123.0,i | 1 | 2 | 3,NaN,1.15,4.55,163931400.0,185346.0,4606.0,19.04,...,4.32,4.52,20.47,NaN,39.74,NaN,735.0,707.0,1.29,NaN
501,SAM,501.0,i | 1 | 2 | 3,NaN,1.30,3.17,5005800.0,6395.0,1359.0,20.31,...,3.99,3.87,5.03,NaN,30.83,NaN,770.0,733.0,-0.24,NaN
448,PRAKIT,448.0,i | 1 | 2 | 3,NaN,9.50,0.00,3300.0,31.0,574.0,21.25,...,3.00,3.14,1.20,4.21,58.38,NaN,797.0,786.0,-1.82,NaN
327,LIT,327.0,i | 1 | 2 | 3,NaN,3.68,0.00,368400.0,1357.0,815.0,21.30,...,6.01,3.70,1.57,4.89,58.96,NaN,787.0,648.0,1.44,NaN
671,TPCS,671.0,i | 1 | 2 | 3,NaN,12.60,0.00,6300.0,82.0,1361.0,21.33,...,2.30,2.75,8.90,4.76,26.49,NaN,806.0,819.0,0.61,NaN
423,PDJ,423.0,i | 1 | 2 | 3,NaN,2.20,0.92,115800.0,253.0,1186.0,22.41,...,1.24,2.45,-1.12,4.55,58.24,NaN,823.0,880.0,-1.08,NaN
308,KSL,308.0,i | 1 | 2 | 3,NaN,3.62,-1.09,5608900.0,20327.0,15965.0,22.58,...,2.96,3.76,10.03,NaN,27.81,NaN,798.0,804.0,1.71,NaN
473,QLT,473.0,i | 1 | 2 | 3,NaN,4.08,0.00,71600.0,291.0,402.0,23.03,...,3.92,4.13,-3.37,7.35,43.10,NaN,789.0,767.0,0.37,NaN

In [56]:
df[(df['P/E'] > 5) &
(df['P/E'] < 20) & 
(df['Yield%'] > 5)].sort_values(['P/E', 'Yield%','ROE%'], 
ascending=[True, False, False])

,Name,No.,Links,Sign,Last,Chg%,Volume,Value (k),MCap (M),P/E,...,ROA%,ROE%,NPM%,Yield%,FFloat%,MG%,Magic1,Magic2,PEG,CG
528,SENA,528.0,i | 1 | 3,NaN,3.96,0.00,810200.0,3198.0,5686.0,5.11,...,9.23,16.74,25.53,7.87,32.25,NaN,168.0,236.0,0.09,NaN
43,AP,43.0,i | 1 | 2 | 3,NaN,8.40,0.60,5562200.0,46413.0,26426.0,5.28,...,10.23,17.14,14.56,5.36,65.00,NaN,163.0,206.0,0.99,NaN
658,TNITY,658.0,i | 1 | 3,NaN,6.70,0.00,426300.0,2861.0,1437.0,5.74,...,7.39,16.06,23.37,7.46,52.59,NaN,183.0,302.0,0.21,NaN
348,MCS,348.0,i | 1 | 2 | 3,XD,14.60,0.00,2778800.0,40395.0,6964.0,5.99,...,24.01,31.31,21.75,6.85,87.47,NaN,62.0,39.0,0.35,NaN
598,SUTHA,598.0,i | 1 | 2 | 3,NaN,4.50,-1.75,110900.0,502.0,1350.0,6.07,...,12.48,40.83,5.92,6.22,22.19,NaN,38.0,150.0,-0.25,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,FSMART,211.0,i | 1 | 2 | 3,NaN,10.60,-2.75,4030000.0,42969.0,8480.0,17.29,...,17.59,39.97,14.53,5.66,34.77,NaN,266.0,304.0,0.76,NaN
621,TEAMG,621.0,i | 1 | 2 | 3,NaN,2.42,3.42,10392200.0,25014.0,1646.0,17.97,...,5.93,9.78,5.10,6.61,54.01,NaN,566.0,613.0,9.54,NaN
471,Q-CON,471.0,i | 1 | 3,NaN,5.20,-0.95,105500.0,553.0,2080.0,19.46,...,5.70,5.43,10.38,8.85,15.00,NaN,704.0,639.0,-0.14,NaN
742,WHAUP,742.0,i | 1 | 2 | 3,NaN,4.26,0.00,2832100.0,12037.0,16295.0,19.68,...,4.92,6.89,31.27,5.93,25.59,NaN,671.0,690.0,0.13,NaN
365,MODERN,365.0,i | 1 | 2 | 3,NaN,3.56,-1.11,192600.0,688.0,2670.0,19.68,...,5.62,6.17,4.43,5.62,68.74,NaN,682.0,642.0,-0.81,NaN