In [1]:
import quandl

In [2]:
quandl.ApiConfig.api_key = 'fwmSYW-UsHMJth1gJ_eC'

In [3]:
start = '2015-01-01'
end = '2022-01-28'

In [16]:
msft = quandl.get('CMHC/HPPU50_BC', start_date=start, end_date=end)

In [17]:
msft

,1st 20%,2nd 40%,3rd 60%,4th 80%,Median,Average,Units
Date,,,,,,,
2015-01-31,500000.0,710000.0,1125000.0,1830000.0,895000.0,1298428.0,1578.0
2015-02-28,511000.0,722000.0,1170000.0,1860000.0,900000.0,1308609.0,1555.0
2015-03-31,520000.0,730000.0,1190000.0,1900000.0,900000.0,1323959.0,1466.0
2015-04-30,500000.0,720000.0,1179000.0,1957000.0,900000.0,1345008.0,1397.0
2015-05-31,490000.0,715000.0,1126000.0,1898000.0,882500.0,1326155.0,1426.0
...,...,...,...,...,...,...,...
2020-11-30,870000.0,1245000.0,1640000.0,2542000.0,1450000.0,1924937.0,1051.0
2020-12-31,868000.0,1300000.0,1700000.0,2700000.0,1500000.0,2002640.0,982.0
2021-01-31,869000.0,1300000.0,1656000.0,2680000.0,1500000.0,1963242.0,943.0
2021-02-28,877000.0,1300000.0,1650000.0,2730000.0,1480000.0,1993903.0,906.0
2021-03-31,864000.0,1300000.0,1722000.0,2842000.0,1490000.0,2047765.0,826.0